data<-read.table("household_power_consumption.txt", header=FALSE,na.strings="?",sep=";",skip=66637,nrows=2880,col.names=c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
as.Date(data$Date,format="%d/%m/%Y")
DayTime<-strptime(paste(data$Date,data$Time),"%d/%m/%Y %H:%M:%S")
png(filename="plot4.png", width=480, height=480)
par(mfrow=c(2,2),mar=c(4,4,3,2),oma=c(0,0,0,0))
with(data,{
        plot(DayTime,data$Global_active_power, type="l",ylab="Global Active Power",xlab="")
        plot(DayTime,data$Voltage, type="l", xlab="datetime", ylab="Voltage")
        plot(DayTime,data$Sub_metering_1, type="l",ylab="Energy sub metering",xlab="")
                lines(DayTime,data$Sub_metering_2, col="red", type="l")
                lines(DayTime,data$Sub_metering_3, col="blue", type="l")
                legend("topright",bty="n", lty=1, lwd= 1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
        plot(DayTime,data$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
})
dev.off